version: "3.9"
services:
  frontend:
    build: "./frontend"
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/webpack.config.ts:/code/webpack.config.ts
